In [9]:
import numpy as np

# Task 1
vector_1 = np.arange(1, 11)
print("1D array with the first 10 positive integers:\n", vector_1)

1D array with the first 10 positive integers:
 [ 1  2  3  4  5  6  7  8  9 10]


In [10]:
# Task 2
matrix_3x3 = np.zeros((3,3))
print("3x3 matrix filled with zeros:\n", matrix_3x3)

3x3 matrix filled with zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# Task 3
matrix_5x5 = np.random.randint(1, 11, size=(5, 5))
print("5x5 matrix filled with random integers from 1 to 10:\n", matrix_5x5)

5x5 matrix filled with random integers from 1 to 10:
 [[ 2  3  8  1  6]
 [ 9  9  8  2 10]
 [ 9 10  2  4  7]
 [ 7  5  3  4  8]
 [ 4  8  7  7 10]]


In [13]:
# Task 4
matrix_4x4 = np.random.rand(4, 4)
print("4x4 matrix filled with random floats between 0 and 1:\n", matrix_4x4)

4x4 matrix filled with random floats between 0 and 1:
 [[0.27061125 0.61741509 0.24775334 0.20001968]
 [0.42471235 0.00890828 0.33504347 0.69915217]
 [0.79578417 0.54887639 0.74940651 0.44683839]
 [0.94954847 0.05368986 0.52237431 0.9512908 ]]


In [21]:
# Task 5
array_1 = np.random.randint(1, 11, size=5)
array_2 = np.random.randint(1, 11, size=5)

addition = array_1 + array_2
subtraction = array_1 - array_2
multiplication = array_1 * array_2

print("Array 1:\n", array_1)
print("Array 2:\n", array_2)
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
      

Array 1:
 [10 10  5  3 10]
Array 2:
 [5 4 5 7 6]
Addition:
 [15 14 10 10 16]
Subtraction:
 [ 5  6  0 -4  4]
Multiplication:
 [50 40 25 21 60]


In [24]:
# Task 6
vector_7_1 = np.random.rand(7)
vector_7_2 = np.random.rand(7)

dot_product = np.dot(vector_7_1, vector_7_2)
print("Dot product of two vectors:\n", dot_product)

Dot product of two vectors:
 2.755455484083356


In [5]:
import numpy as np
# Task 7
matrix_2x2 = np.random.randint(1, 11, size=(2, 2))
matrix_2x3 = np.random.randint(1, 11, size=(2, 3))


product = np.dot(matrix_2x2, matrix_2x3)
print("Product of 2x2 and 2x3 matrices:\n", product)

Product of 2x2 and 2x3 matrices:
 [[45 16 36]
 [61 58 66]]


In [7]:
# Task 8
matrix_3x3 = np.random.randint(1, 11, size =(3, 3))
inverse = np.linalg.inv(matrix_3x3)
print("3x3 matrix:\n", matrix_3x3)
print("Inverse of the 3x3 matrix:\n", inverse)

3x3 matrix:
 [[4 4 9]
 [9 7 2]
 [9 4 3]]
Inverse of the 3x3 matrix:
 [[-0.05726872 -0.10572687  0.24229075]
 [ 0.03964758  0.30396476 -0.3215859 ]
 [ 0.11894273 -0.08810573  0.03524229]]


In [9]:
# Task 9
matrix_4x4 = np.random.rand(4, 4)
transpose = np.transpose(matrix_4x4)
print("4x4 matrix:\n", matrix_4x4)
print("Transpose of the 4x4 matrix:\n", transpose)

4x4 matrix:
 [[0.73033159 0.52958794 0.45911231 0.55744929]
 [0.2315788  0.28454973 0.3357443  0.21898473]
 [0.40454443 0.05825236 0.54196918 0.85073792]
 [0.75814257 0.59662043 0.10472092 0.24195631]]
Transpose of the 4x4 matrix:
 [[0.73033159 0.2315788  0.40454443 0.75814257]
 [0.52958794 0.28454973 0.05825236 0.59662043]
 [0.45911231 0.3357443  0.54196918 0.10472092]
 [0.55744929 0.21898473 0.85073792 0.24195631]]


In [10]:
# Task 10
matrix_3x4 = np.random.randint(1, 11, size=(3, 4))
vector_4 = np.random.randint(1, 11, size=4)

result = np.dot(matrix_3x4, vector_4)
print("3x4 matrix:\n", matrix_3x4)
print("4-element vector:\n", vector_4)
print("product of matrix and vector:\n", result)

3x4 matrix:
 [[ 6  6  9  1]
 [ 4  9  3 10]
 [ 4  9  8  2]]
4-element vector:
 [ 4  9  4 10]
product of matrix and vector:
 [124 209 149]


In [14]:
# Task 11
matrix_2x3 = np.random.rand(2, 3)
vector_3 = np.random.rand(3)

result = np.dot(matrix_2x3, vector_3)
print("2x3 matrix:\n", matrix_2x3)
print("3-element vector:\n", vector_3)
print("Product of matrix and vector:\n", result)

2x3 matrix:
 [[0.58565479 0.97826303 0.93982504]
 [0.95163763 0.57732818 0.16834466]]
3-element vector:
 [0.9823963  0.80281496 0.80922819]
Product of matrix and vector:
 [2.12124221 1.53460222]


In [18]:
# Task 12
matrix_2x2_a = np.random.randint(1, 11, size=(2, 2))
matrix_2x2_b = np.random.randint(1, 11, size=(2, 2))
hadamard_product = np.multiply(matrix_2x2_a, matrix_2x2_b)
print("First 2x2 matrix:\n", matrix_2x2_a)
print("Second 2x2 matrix:\n", matrix_2x2_b)
print("Element-wice product (Hadamard product):\n", hadamard_product)

First 2x2 matrix:
 [[ 7  7]
 [ 8 10]]
Second 2x2 matrix:
 [[3 9]
 [6 7]]
Element-wice product (Hadamard product):
 [[21 63]
 [48 70]]


In [20]:
# Task 13
matrix_2x2_a = np.random.randint(1, 11, size=(2, 2))
matrix_2x2_b = np.random.randint(1, 11, size=(2, 2))

matrix_product = np.dot(matrix_2x2_a, matrix_2x2_b)
print("First 2x2 matrix:\n", matrix_2x2_a)
print("Second 2x2 matrix:\n", matrix_2x2_b)
print("Matrix product:\n", matrix_product)

First 2x2 matrix:
 [[10  2]
 [10  2]]
Second 2x2 matrix:
 [[10  2]
 [ 2  2]]
Matrix product:
 [[104  24]
 [104  24]]


In [21]:
# Task 14
matrix_5x5 = np.random.randint(1, 101, size=(5, 5))
matrix_sum = np.sum(matrix_5x5)
print("5x5 matrix:\n", matrix_5x5)
print("Sum of all elements:\n", matrix_sum)

5x5 matrix:
 [[70 25 22 84 32]
 [61 40 71 96 11]
 [99 58 27 69  2]
 [97 32  1 35 78]
 [71 20 62 75 17]]
Sum of all elements:
 1255


In [22]:
# Task 15
matrix_4x4_a = np.random.randint(1, 11, size=(4, 4))
matrix_4x4_b = np.random.randint(1, 11, size=(4, 4))

difference = matrix_4x4_a - matrix_4x4_b
print("First 4x4 matrix:\n", matrix_4x4_a)
print("Second 4x4 matrix:\n", matrix_4x4_b)
print("Difference of matrices:\n", difference)


First 4x4 matrix:
 [[ 6  3  1  6]
 [10  9  6  8]
 [10  9  6  6]
 [ 9 10  3  8]]
Second 4x4 matrix:
 [[ 1 10  2  5]
 [ 3  3  1  6]
 [ 7  9  7  6]
 [10  7  6  9]]
Difference of matrices:
 [[ 5 -7 -1  1]
 [ 7  6  5  2]
 [ 3  0 -1  0]
 [-1  3 -3 -1]]


In [23]:
# Task 16 
matrix_3x3 = np.random.rand(3, 3)
row_sums = np.sum(matrix_3x3, axis=1).reshape(-1, 1)
print("3x3 matrix:\n", matrix_3x3)
print("Column vector of row sums:\n", row_sums)

3x3 matrix:
 [[0.85123786 0.56608477 0.46485261]
 [0.48985634 0.21795403 0.31350675]
 [0.03947974 0.82858465 0.93396934]]
Column vector of row sums:
 [[1.88217524]
 [1.02131712]
 [1.80203373]]


In [25]:
# Task 17
matrix_3x4 = np.random.randint(1, 11, size=(3, 4))
squared_matrix = np.square(matrix_3x4)
print("3x4 matrix:\n", matrix_3x4)
print("Matrix with squares of the elements:\n", squared_matrix)

3x4 matrix:
 [[ 3  9  3  1]
 [10  7  5  5]
 [ 3  8  5  9]]
Matrix with squares of the elements:
 [[  9  81   9   1]
 [100  49  25  25]
 [  9  64  25  81]]
